jokes = [
    "Telling my daughter garlic is good for you. Good immune system and keeps pests away.Ticks, mosquitos, vampires... men.",
    "I've been going through a really rough period at work this week It's my own fault for swapping my tampax for sand paper.",
    "If I could have dinner with anyone, dead or alive... ...I would choose alive. -B.J. Novak-",
    "Two guys walk into a bar. The third guy ducks.",
    "Why was the musician arrested? He got in treble.",
    "Did you hear about the guy who blew his entire lottery winnings on a limousine? He had nothing left to chauffeur it.",
    "He was a real gentlemen and always opened the fridge door for me",
    "What should you do before criticizing Pac-Man? WAKA WAKA WAKA mile in his shoes",
    "What's the difference between an illegal Mexican and an autonomous robot...? Nothing... they were both made to steal American jobs.",
    "What do you call a barbarian you can't see? an Invisigoth.",
    "How do you spell Canda? C,eh,N,eh,D,eh",
    "You ever notice that the most dangerous thing about marijuana is getting caught with it?",
    "What did Arnold Schwarzenegger say at the abortion clinic? Hasta last vista, baby.",
    "My wife is in a bad mood. I think her boyfriend forgot their anniversary. Way to go, dude. Now we all suffer...",
    "My speech today will be like a mini-skirt. Long enough to cover the essentials but short enough to hold your attention!",
    "Thanksgiving joke What does Miley Cyrus eat for Thanksgiving? Twerky! Just kidding... Drugs. She eats drugs. -Adam Zopf @adamzopf",
    "Why do you never see elephants hiding in trees? 'Cause they are freaking good at it",
    "How did the blonde die raking leaves? She fell out of the tree.",
    "That guy is such a douche-bag! Is he single? Maybe I can fix him!""  women",
    "My son just got a tattoo of a heart, a spade, a club, and a diamond, all without my permission. I guess I'll deal with him later.",
    "What do you call a potato in space? Spudnik",
    "What happens to a necrophiliac after death? Reserection",
    "Why did the chicken hold a seance? To get to the other side.",
    "Where do baby cows go to eat lunch? At the calf-eteria.",
    "What's the difference between a painting and Jesus. You only require one nail to put up the painting.",
    "Mom: ""Do you want this?"" Me: ""No."" Mom: ""Ok I'll give it to your brother."" Me: ""No I want it.",
    "Yttrium-barium-copper oxide walks into a bar The bartender tells him, ""We don't serve superconductors here."" He leaves without resistance.",
    "A guy pick up a woman Then he puts her down",
    "Ibuprofen is my favorite headache medicine that also sounds like a reggae professor.",
    "Before I destroy a wasp's nest I like to capture a single wasp and tell it my entire diabolical plan.",
    "What's Al-Qaeda's favorite American football team? The New York jets.",
    "Someone didnt click the button in /r/thebutton Yeah... Thats a good joke , he impossible!",
    "With Facebook, you can stay in touch with people you would otherwise never talk to, but that's only one of the many awful things about it",
    "What's the difference between a blonde and a washer? When you dump your load in a washer, it doesn't follow you around for a week.",
    "Have you ever heard of the movie ""Constipation""? No? Most likely because it never came out.",
    "What's black, blue and doesn't look too well? Stevie Wonder",
    "I saw a French rifle on eBay today It's never been fired but I heard it was dropped once.",
    "What did the car said to the valet? I've been through a lot.",
    "A Mexican fireman had twin boys He named them Jose and Hose B",
    "Things have really turned around for me since I re-named my penis and testicles ""JD Power and Associates"".",
    "My sex face is the same as my first pee in three hours face.",
    "My cat just walked by me carrying a toy mouse I don't remember buying her. Women be shoppin!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
    "Why did the Xbox owner cross the road? To fuck your mom.",
    "Sometimes you check the amount of subscribed people. When you do this, there are 4,111,093,0003.666 ""humorists"". 2/3rds of a person? Really?",
    "I don't believe in Bigfoot; because he never believed in me. I'd scan the crowd at my ballet recitals, and always see that one empty seat.",
    "Why were the baker's hands brown? Because he kneaded a poo.",
    "Not to get too technical, but chemistry says alcohol IS a solution. So I win.",
    "I often think if I'd taken a different path in life, I could be lying on a slightly more comfortable sofa right now.",
    "What do grandparents smell like? ""Depends",
    "7% of all hearing loss is a result of sitting in a restaurant next to a table full of women who just received dessert.",
    "What do people from the 1930's and /r/news jokes have in common? They're both old.",
    "I like my slaves like I like my coffee Fair Trade.",
    "ME: I fell off a 50 ft tall ladder once GIRL: holy cow how did you survive ME: I fell off the bottom rung",
    "What do you call a blind dinosaur? A do-think-he-saurus :) !! Lol What do you call a blind dinosaurs dog? A do-you-think-he-saurus-rex",
    "I just bought a very tiny amphibian for a pet. It's my-newt!",
    "This may be not be a mainstream opinion, but I don't believe you should cut down a Christmas tree unless you intend on eating it.",
    "Jenna Jameson to Oprah, ""There's a little bit of Jenna Jameson in everyone."" I'm pretty sure she got that backwards.",
    "Even after 20 years, Jared Fogle is still getting into smaller and smaller jeans.",
    "I have a degree in men's studies. It's called ""world history"". #TRUMP 2016! YOU CAN'T STUMP THE TRUMP!",
    "Why don't most fans like the first 39 episodes of DBZ? Its pretty gay, just Saiyan.",
    "My ex-wife still misses me... But her aim is gettin better.",
    "This doctor once told me eating a bagel was like eating 5 slices of bread and I was like ok, cool, I like bread",
    "What did the two tampons say to each other? Nothing, they're both stuck-up cunts.",
    "What do you call Jay-Z having a leg transplant? A hip-hop hip op.",
    "What defies the law of gravity? Women. They heavier they are, the easier they are to pick up.",
    "Everything has to be related in a woman: if the mouth shuts, the legs open.",
    "Wanna hear a pun about long hair? Rapunzel.",
    "What's the difference Donald Trump and my Vagina? One's a Cunt and the other has nice hair.",
    "My doctor had to put me on a new medication that's supposed to help lower the amount of karate in my blood",
    "[uses the restroom] Wife: make sure to put the toilet seat down Me: okay Me: [to toilet seat] you're worthless and nobody likes you",
    "Q: What's the difference between a blonde and a supermarket trolley? A: The supermarket trolley has a mind of its own.",
    "You know... When someone says to you ""Jesus loves you."" It's always comforting. Unless you are in a Mexican jail.",
    "When I hear ""This call is being monitored for quality assurance"" I think ""Cool, let's see how bad this person wants their job.",
    "You know what the definition of ""competitive"" is? Finishing first *and* third in a circlejerk.",
    "How do you know if your wine was made in the 90's? It smells like teen spirit.",
    "I'll Never forget my Grandpa's last words to me ""Are you still holing the lader?"",
    "Even people who are good for nothing have the capacity to bring a smile to your face. For example, when you push them down the stairs.",
    "I visited my friend at his new house. He told me to make myself at home, so I threw him out. I hate visitors.",
    "Imagine if you walked into a bar and there was a long line of people waiting to punch you. That’s the punch line",
    "What’s the difference between me and cancer? My dad didn’t beat cancer.",
    "My parents raised me as an only child, which really pissed off my sister.",
    "Why can’t Michael Jackson go within 500 metres of a school? Because he’s dead",
    "I had a crush on my teacher, which was confusing, because I was homeschooled.",
    "Today was a terrible day. My ex got hit by a bus. And I lost my job as a bus driver!",
    "What makes sad people jump? Bridges.",
    "When I die, I want to die peacefully in my sleep, like my grandfather. Not screaming and yelling like the passengers in his car.",
    "“Just say NO to drugs!” Well, If I am talking to my drugs, I probably already said yes.",
    "When does a joke become a dad joke? When it leaves and never comes back.",
    "What do my dad and Nemo have in common? They both can’t be found."]
